#!/usr/bin/env bash
# Install aXism into the user environment and ensure the binary is on PATH.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "Installing aXism from: $ROOT"

# Bake short commit into the wheel so installed binaries know their revision.
BUILD_INFO="src/axism/_build_info.py"
COMMIT="$(git rev-parse --short=7 HEAD 2>/dev/null || true)"
AXISM_COMMIT="$COMMIT" python3 -c '
import os
from pathlib import Path
Path("src/axism/_build_info.py").write_text(
    "# Generated by scripts/install.sh — do not edit.\n"
    "COMMIT = %r\n" % os.environ.get("AXISM_COMMIT", "")
)
'
restore_build_info() {
  printf '%s\n' \
    '# Overwritten by scripts/install.sh when packaging; leave empty for source checkouts' \
    '# (runtime falls back to git rev-parse).' \
    'COMMIT = ""' \
    > "$BUILD_INFO"
}
trap restore_build_info EXIT

if command -v uv >/dev/null 2>&1; then
  uv tool install --force .
elif command -v pipx >/dev/null 2>&1; then
  pipx install --force .
else
  python3 -m pip install --user --upgrade .
fi

BIN_DIR="${HOME}/.local/bin"
if [[ ":$PATH:" != *":${BIN_DIR}:"* ]]; then
  echo
  echo "Add ${BIN_DIR} to your PATH, for example:"
  echo "  export PATH=\"${BIN_DIR}:\$PATH\""
  echo "Add that line to ~/.bashrc or ~/.zshrc to keep it."
fi

if command -v axism >/dev/null 2>&1; then
  echo
  axism --version
  echo "Ready. Run: axism"
else
  echo
  echo "axism not found on PATH yet. Try: ${BIN_DIR}/axism --version"
fi
